# First source plugins
# autosuggestions
if [[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
# syntax highlighting
if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
autoload -Uz compinit promptinit
promptinit
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump"
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select
zstyle ":completion:*:commands" rehash 1

# cd just by typing name
setopt autocd
# allow comments in interactive mode
setopt interactivecomments
# hide error message if nothing is found
setopt nonomatch
# report status of background jobs immediately
setopt notify
# sort items from A-Z when it makes sense
setopt numericglobsort
# enable command substitution in the prompt
setopt promptsubst
# don't consider certain chars part of the word
WORDCHARS=${WORDCHARS//\/}
# hide '%' sign
PROMPT_EOL_MARK=""
# shell navigation
bindkey '^R' history-incremental-search-backward
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[3~' delete-char
# environment variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export GPG_TTY=$(tty)
# shell history settings
HISTFILE="$XDG_CONFIG_HOME/zsh/zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

# configure prompt
PS1='%F{green}%n@%m[%~]$ '
# highlight matches in red with grep
alias grep="grep --color=always"
alias ls="eza --icons --group-directories-first"
alias l="ls"
alias ll="ls -l"
alias la="ls -la"
alias cls="clear"
alias vim="nvim"
alias neofetch="screenfetch"
alias open="xdg-open"
alias xclip="xclip -r -selection clipboard"
alias cat="bat --paging=never"
alias pwnssh="ssh hacker@dojo.pwn.college"
alias exprn="cp ~/code/python/template.py ./exploit.py"
alias venvrn="python -m venv venv; source ./venv/bin/activate"
alias lock="hyprlock"
alias python=python3
