set -g default-terminal "screen-256color"
set -g mouse on
set -g default-command /bin/zsh

# Vim style keybindings for copy and paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Add break pane hotkey
bind-key e break-pane -d -n _exp_stdin

# Remove confirmation for removing panes
bind-key & kill-window
bind-key x kill-pane

# Clipboard options
set -s set-clipboard external

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R
set -g @vim_navigator_prefix_mapping_clear_screen ""
bind y send-keys Enter

# Open panes in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# Open windows in cwd
bind c new-window -c "#{pane_current_path}"

# Start window indexing at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# bind Leader+a -> previous window (was 'p')
bind a previous-window
# bind Leader+s -> next window (was 'n')
bind s next-window

# THEME
