listener {
    # 2.5min.
    timeout = 150
    # Set monitor backlight to minimum, avoid 0 on OLED monitor. Also set keyboard backlight
    on-timeout = brightnessctl -s set 10 && brightnessctl -s --device='*:kbd_backlight' set 0
    # Monitor backlight and keyboard backlight restore.
    on-resume = brightnessctl -r && brightnessctl -r --device='*:kbd_backlight'
}

listener {
    # 5min.
    timeout = 300
    # Avoid starting multiple hyprlock instances.
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    # 20min.
    timeout = 1200
    # Suspend PC.
    on-timeout = systemctl suspend
}

# NOTE: Listeners to dim and turn off screen when hyprlock is manually used
listener {
    timeout = 5
    # Set monitor backlight to minimum, avoid 0 on OLED monitor. Also set keyboard backlight
    on-timeout = pidof hyprlock && brightnessctl -s set 10 && brightnessctl -s --device='*:kbd_backlight' set 0
    # Monitor backlight and keyboard backlight restore.
    on-resume = pidof hyprlock && brightnessctl -r && brightnessctl -r --device='*:kbd_backlight'
}
listener {
    timeout = 15
    # Turn off the display if locked
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action=off})'
    # The normal 5 second listener resume does not persist on suspend
    on-resume = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action=on})' && brightnessctl -r && brightnessctl -r --device='*:kbd_backlight'
}
