# Avoid starting multiple hyprlock instances.
lock_cmd = pidof hyprlock || hyprlock
# Lock before suspend.
before_sleep_cmd = loginctl lock-session
# Avoid having to press a key twice to turn on the display.
after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action=on})'
}

listener {
    # 2.5min.
    timeout = 150
    # Set monitor backlight to minimum, avoid 0 on OLED monitor. Also set keyboard backlight
    on-timeout = brightnessctl -s set 10 && brightnessctl -s --device='*:kbd_backlight' set 0
    # Monitor backlight and keyboard backlight restore.
    on-resume = brightnessctl -r && brightnessctl -r --device='*:kbd_backlight'
}

# Turn off keyboard backlight. Comment out this section if you don't have a keyboard backlight.
listener {
    # 2.5min.
    timeout = 150
    # Turn off keyboard backlight.
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    # Turn on keyboard backlight.
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    # 5min.
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 315
    # Screen off when timeout has passed.
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action=off})'
    # Screen on when activity is detected after timeout has fired.
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action=on})' && brightnessctl -r
}

listener {
    # 20min.
    timeout = 1200
    # Suspend PC.
    on-timeout = systemctl suspend
}

# NOTE: Listeners to dim and turn off screen when hyprlock is manually used
listener {
    timeout = 5
    # Set monitor backlight to minimum, avoid 0 on OLED monitor. Also set keyboard backlight
    on-timeout = pidof hyprlock && brightnessctl -s set 10 && brightnessctl -s --device='*:kbd_backlight' set 0
    # Monitor backlight and keyboard backlight restore.
    on-resume = pidof hyprlock && brightnessctl -r && brightnessctl -r --device='*:kbd_backlight'
}
listener {
    timeout = 15
    # Turn off the display if locked
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action=off})'
    on-resume = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action=on})'
}
