-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
--monitor=,preferred,auto,auto
--monitor = eDP-1, 1920x1200@60, 0x0, 1.3333334
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144",
    position = "0x0",
    scale = "1.0",
})

-- Quick plug monitors with their negotiated settings
--monitor = , preferred, auto, 1
hl.monitor({
    output = "",
    mode = "1920x1080@180",
    position = "auto",
    scale = "1",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal = "alacritty"
local fileManager = "pcmanfm"
local menu = "vicinae toggle"
local browser = "chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --incognito"
local notes = "logseq-desktop-electron --enable-features=UseOzonePlatform --ozone-platform=wayland"
local keepass = "keepassxc"
local discord = "vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland"
local screenshot = "flameshot gui"
local vm = "virt-manager"

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

-- unscale XWayland

hl.env("GDK_SCALE", "2")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({

    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({

    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7,
    bezier = "quick",
})

hl.env("FONT_NAME", "JetBrainsMono Nerd Font 14")
hl.env("DOCUMENT_FONT_NAME", "JetBrainsMono  Nerd Font 14")
hl.env("MONOSPACE_FONT_NAME", "JetBrainsMono Nerd Font 14")
hl.env("FONT_ANTIALIASING", "rgba")
hl.env("FONT_HINTING", "full")

hl.window_rule({
    name = "IDA float fix",
    match = {
        float = true,
        class = "com.hex-rays.ida",
    },
})

hl.window_rule({
    name = "IDA float fix",
    match = {
        float = true,
        title = ".*About.*",
    },
})

hl.window_rule({
    name = "IDA float fix",
    match = {
        title = "title:.*IDA - .*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "IDA float fix",
    match = {
        title = "IDA: Quick start",
    },
    suppress_event = "maximize",
})

hl.layer_rule({
    name = "vicinae-blur",
    match = {
        namespace = "vicinae",
    },
    blur = true,
    -- TODO: manual review — disable "ignore_alpha" has no layer_rule directive analog
})

hl.layer_rule({
    name = "vicinae-no-animation",
    match = {
        namespace = "vicinae",
    },
    no_anim = true,
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "ALT"

hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd(notes))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.exec_cmd(keepass))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd(discord))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(screenshot))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(vm))

hl.bind(mainMod .. " + j", hl.dsp.window.cycle_next({ next = true }))
hl.bind(mainMod .. " + k", hl.dsp.window.cycle_next({ next = true } --[[ cyclenext: unrecognized arg(s) "-1" ]]))
hl.bind(mainMod .. " + l", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + h", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })

hl.bind(mainMod .. " + RETURN", hl.dsp.layout("swapwithmaster master"))
hl.bind("SUPER + d", hl.dsp.layout("removemaster"))

hl.bind(mainMod .. " + TAB", hl.dsp.focus({ workspace = "previous" }))

hl.bind("SUPER + 1", hl.dsp.focus({ monitor = 0 }))
hl.bind("SUPER + 2", hl.dsp.focus({ monitor = 1 }))
hl.bind("SUPER + 3", hl.dsp.focus({ monitor = 2 }))
hl.bind("SUPER + 4", hl.dsp.focus({ monitor = 3 }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ monitor = "0" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ monitor = "1" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ monitor = "2" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ monitor = "3" }))

hl.bind(mainMod .. " + 1", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 1"))
hl.bind(mainMod .. " + 2", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 2"))
hl.bind(mainMod .. " + 3", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 3"))
hl.bind(mainMod .. " + 4", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 4"))
hl.bind(mainMod .. " + 5", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 5"))
hl.bind(mainMod .. " + 6", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 6"))
hl.bind(mainMod .. " + 7", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 7"))
hl.bind(mainMod .. " + 8", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 8"))
hl.bind(mainMod .. " + 9", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 9"))
hl.bind(mainMod .. " + 0", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh workspace 10"))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 1"))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 2"))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 3"))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 4"))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 5"))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 6"))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 7"))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 8"))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 9"))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.exec_cmd("~/.config/hypr/WorkspaceAction.sh movetoworkspace 10"))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    -- Ignore maximize requests from all apps. You'll probably like this.
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    -- Fix some dragging issues with XWayland
    no_focus = true,
})

hl.bind(mainMod .. " + m", hl.dsp.group.toggle())
hl.bind(mainMod .. " + j", hl.dsp.group.next())
hl.bind(mainMod .. " + k", hl.dsp.group.prev())

-- TODO: manual review — top-level key 'enabled = false' has no enclosing section
-- TODO: manual review — top-level key 'enabled = false' has no enclosing section
hl.config({
    xwayland = {
        force_zero_scaling = false,
    },
    -- toolkit-specific scale
    --##################
    --## PERMISSIONS ###
    --##################
    -- See https://wiki.hypr.land/Configuring/Permissions/
    -- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
    -- for security reasons
    -- ecosystem {
    --   enforce_permissions = 1
    -- }
    -- permission = /usr/(bin|local/bin)/grim, screencopy, allow
    -- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
    -- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
    --####################
    --## LOOK AND FEEL ###
    --####################
    -- Refer to https://wiki.hypr.land/Configuring/Variables/
    -- https://wiki.hypr.land/Configuring/Variables/#general
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 1,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = { colors = { "rgb(59278f)", "rgb(59278f)" } },
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "master",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#decoration
    decoration = {
        rounding = 2,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hypr.land/Configuring/Variables/#animations

    animations = {
        enabled = false,
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
    -- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- workspace = w[tv1], gapsout:0, gapsin:0
    -- Change fonts
    --theme {
    --    font = JetBrainsMono NF
    --    font_size = 12
    --}
    -- blur
    -- disable animation for vicinae only
    -- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
    dwindle = {
        --pseudotile = true, -- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hypr.land/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
        repeat_delay = 200,
        repeat_rate = 50,
    },
    -- See https://wiki.hypr.land/Configuring/Gestures
    -- Example per-device config
    -- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hypr.land/Configuring/Keywords/
    -- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
    --bind = $mainMod, P, pseudo, # dwindle
    --bind = $mainMod, J, togglesplit, # dwindle
    -- Move focus with mainMod + arrow keys
    -- focus master window
    -- remove focused window from the master stack
    -- Switch to previous workspace
    -- Example special workspace (scratchpad)
    --bind = $mainMod, S, togglespecialworkspace, magic
    --bind = $mainMod SHIFT, S, movetoworkspace, special:magic
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Laptop multimedia keys for volume and LCD brightness
    -- Requires playerctl
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
    -- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
    -- Example windowrule
    -- windowrule = float,class:^(kitty)$,title:^(kitty)$
    -- Add monocle mode behaviour
    group = {
        insert_after_current = true,
        focus_removed_window = true,
        groupbar = {
            enabled = true,
            render_titles = false,
            height = 4,
        },
    },
    -- Fix cursor lag on NVIDIA cards
    cursor = {
        no_hardware_cursors = true,

    },
    -- Recommended battery saving settings

    -- TODO: manual review — unexpected token after 'decoration'
    -- TODO: manual review — unexpected token after 'decoration'
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar & hyprpaper & hypridle")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("vicinae server")
end)

