# NOTE: Preferably hyprlock listener should be able to be divided
#       by both screen dim and dpms timeouts for accurate timings

listener {
    # 5min.
    timeout = 300
    # Avoid starting multiple hyprlock instances.
    on-timeout = pidof hyprlock || hyprlock
}

# NOTE: Dim and turn off screen when hyprlock is manually used
#       Do note that these are not ran every 5 seconds,
#       but rather only after the first 5 seconds of inactivity,
#       hence why we need additional listeners for the idling out case
listener {
    timeout = 5
    # If hyprlock process exists
    condition_cmd = pidof hyprlock
    # Set monitor backlight to minimum, avoid 0 on OLED monitor. Also set keyboard backlight
    on-timeout = pidof hyprlock && brightnessctl -s set 10 && brightnessctl -s --device='*:kbd_backlight' set 0
    # Monitor backlight and keyboard backlight restore.
    on-resume = pidof hyprlock && brightnessctl -r && brightnessctl -r --device='*:kbd_backlight'
    condition_retry = 5
}
listener {
    timeout = 15
    # If hyprlock process exists
    condition_cmd = pidof hyprlock
    # Turn off the display if locked
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action=off})'
    # No on-resume: Hyprland must manage this using misc options *_enables_dpms otherwise things break badly
    condition_retry = 15
}

listener {
    # 20min.
    timeout = 1200
    # Suspend PC.
    on-timeout = systemctl suspend
}
