[colors.bright]
black = "#8b949e"
blue = "#a5d6ff"
cyan = "#b3f0ff"
green = "#7ee787"
magenta = "#eddaff"
red = "#ffbaba"
white = "#ffffff"
yellow = "#f2cc60"

[colors.normal]
black = "#7a828e"
blue = "#79c0ff"
cyan = "#56d4dd"
green = "#56d364"
magenta = "#d2a8ff"
red = "#ffa198"
white = "#f0f3f6"
yellow = "#e3b341"

[colors.primary]
background = "#0a0c10"
foreground = "#f0f3f6"

[colors.search.matches]
foreground = "#0a0c10"
background = "#56d364"

[colors.search.focused_match]
foreground = "#0a0c10"
background = "#e3b341"

[colors.footer_bar]
background = "#272b33"
foreground = "#f0f3f6"

[colors.hints.start]
foreground = "#0a0c10"
background = "#e3b341"

[colors.hints.end]
foreground = "#e3b341"
background = "#272b33"
